### PR TITLE
Add Location Controller

### LINKED ISSUE #9: Add Location Controller and Tests
# Acceptance Criteria:

- [ ] There is <tt>LocationController.java</tt> file in the `src/main/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] <tt>LocationController.java</tt> implements a class that implements an API endpoint that takes in the necessary
      parameters, calls the <tt>LocationQueryService</tt>, and returns the results.
- [ ] The file  <tt>LocationController.java</tt> file make appropriate use of the
      annotations `@Tag`, `@Operation` and `@Parameter` to document the API.
- [ ] The controller endpoint shows up on the Swagger UI page.
- [ ] There is a <tt>LocationControllerTests.java</tt> file in the `src/test/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] The tests in <tt>LocationControllerTests</tt> provide 100% coverage of <tt>LocationController</tt> for both jacoco and pitest.

# Details

See the assignment description at https://ucsb-cs156.github.io/w24/lab/team01 for details.

### PR DESCRIPTION
**Pull request by aqiu28517**
In this PR, we add an endpoint `/api/location/get` that can be used to get a list of locations that match a given location name.

dev deployment: http://team01-aqiu28517-dev.dokku-06.cs.ucsb.edu/

Closes #9

### CODE REVIEW

**Comment by jiaqiguan2003** [comment]
LGTM!

**Review by jonathan-herring — APPROVED** [review]
LGTM

**Review by jiaqiguan2003 — APPROVED** [review]
LGTM

**Review by Maria-Saucedo — APPROVED** [review]
LGTM

**Review by Maria-Saucedo — CHANGES_REQUESTED** [review]
For Line 21, the tag link according to the staff example should be "Location info from nominatim.org", you don't need openstreetmap specified (staff example linked below, the instructions on team01 say we'll be graded based on if it matches)

Other than that everything in your dev deployment looks solid! 
http://team01.dokku-00.cs.ucsb.edu/swagger-ui/index.html

**Comment by aqiu28517** [comment]
> For Line 21, the tag link according to the staff example should be "Location info from nominatim.org", you don't need openstreetmap specified (staff example linked below, the instructions on team01 say we'll be graded based on if it matches)
> 
> Other than that everything in your dev deployment looks solid! http://team01.dokku-00.cs.ucsb.edu/swagger-ui/index.html

Fixed, thanks!

**Review by Maria-Saucedo — APPROVED** [review]
Thanks for the quick fix, LGTM!

**Pull request merged**
