### PR TITLE
Add Joke Controller and Tests

### LINKED ISSUE #7: Add Joke Controller and Tests
# Acceptance Criteria:

- [ ] There is <tt>JokeController.java</tt> file in the `src/main/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] <tt>JokeController.java</tt> implements a class that implements an API endpoint that takes in the necessary
      parameters, calls the <tt>JokeQueryService</tt>, and returns the results.
- [ ] The file  <tt>JokeController.java</tt> file make appropriate use of the
      annotations `@Tag`, `@Operation` and `@Parameter` to document the API.
- [ ] The controller endpoint shows up on the Swagger UI page.
- [ ] There is a <tt>JokeControllerTests.java</tt> file in the `src/test/java/edu/ucsb/cs156/spring/backend/controllers` directory.
- [ ] The tests in <tt>JokeControllerTests</tt> provide 100% coverage of <tt>JokeController</tt> for both jacoco and pitest.

# Details

See the assignment description at https://ucsb-cs156.github.io/w24/lab/team01 for details.

### PR DESCRIPTION
**Pull request by jonathan-herring**
In this PR, we add an endpoint `/api/jokes/get` that can be used to get a number of jokes of a specified category

dev deployment: http://team01-jonathan-herring-dev.dokku-06.cs.ucsb.edu/

image

Closes #7

### CODE REVIEW

**Comment by jiaqiguan2003** [comment]
LGTM!

**Review by jiaqiguan2003 — APPROVED** [review]
LGTM

**Review by Maria-Saucedo — CHANGES_REQUESTED** [review]
dokku dev deploy isn't synced to the latest version, but when reviewing your JokesController.java file I could see that your descriptions didn't match what was given to us by the staff example (linked below) 

Please change "ResponseEntity<String> getEarthquakes(" to getJokes (line 34) 

Please match your parameters' examples and text to the staff example, i double checked team01 on the class website, and matching our UI to the staff solution is a portion of the grade:
http://team01.dokku-00.cs.ucsb.edu/swagger-ui/index.html

Thank you!

**Review by Maria-Saucedo — APPROVED** [review]

**Comment by Maria-Saucedo** [comment]
LGTM

**Comment by livitsimple** [comment]
LGTM!

**Review by livitsimple — APPROVED** [review]
LGTM!

**Review by aqiu28517 — APPROVED** [review]
Dev deployment isn't synced, so I tested on localhost. LGTM!

**Pull request merged**
